Make application interactive
BenjaminMatembe/To_Do_List pull request #4
Opened 2023-05-05 12:05 UTC by BenjaminMatembe

On this feature I:

- Added functionality to make the application interactive i.e the user can mark task completion by selecting the corresponding checkbox or undo by unchecking it.The updated task list will be stored in local storage

- I updated the refresh button with a function for the "Clear all completed" button todos.

- Stored the updated array of items in local storage, so the user can get the correct list of values after the page reloads.

2023-05-05 12:30 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @BenjaminMatembe :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following GitHub Flow
✔️ Following some requirements
✔️ App is working 90% 👍
Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 12:30 UTC, HAMMAS-SALEEM commented on src/index.js
> +  window.location.reload();
- [ ] It would be nice if your app should not reload while clearing the completed task 🤔 because right now your app reloads after clearing the completed todos 😨 which is not expected behavior 🤔 It would be nice if you follow the project requirements and your app won't reload while doing the crud operations 👍

**Hint:** Kindly make a display method to display todos after doing crud operations 👍 What this method will do ⬇️
1. First it will clear all take the localStorage and filter the completed items
2. Second, it will remove all the todos from your DOM
3. Third it will render a new list of todos from local storage

2023-05-05 12:30 UTC, HAMMAS-SALEEM commented on src/index.js
### [OPTIONAL REQUIREMENTS]

- [ ] It would be nice if you add some more meaningful features in the Key Feature section to make your readme more descriptive and professional 👍
- [ ] It would be nice if you add more details to your project summary in your readme to make your readme descriptive and more professional and useful 😊

2023-05-06 08:13 UTC, ABDULALI3468 approved these changes
Hi @BenjaminMatembe , 👍 

# APPROVED 💯 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights 
☑️Implemented changes asked by the previous CR.
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 08:57 UTC, BenjaminMatembe commented
Hi @HAMMAS-SALEEM Thank you for the insight given on my code it really helped a lot. Hi @ABDULALI3468 Thank you for approving my pull request.

2023-05-06 08:58 UTC, merged